{
 "title": "Router dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"router\"} | json | line_format `{{.level}} {{.message}}`"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "http.server.request.duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "http.server.request.duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, graphql_operation_name) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{graphql_operation_name}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "http.client.request.duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GraphQL errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(apollo_router_graphql_error_total[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Query planner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Compute job wait time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, job_type) (rate(apollo_router_compute_jobs_queue_wait_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{job_type}}"
    }
   ]
  },
  {
   "title": "Compute job execution time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, job_type) (rate(apollo_router_compute_jobs_execution_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{job_type}}"
    }
   ]
  },
  {
   "title": "Cache hit percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "apollo_router_cache_hit_time_count{storage=\"memory\"} / (apollo_router_cache_hit_time_count{storage=\"memory\"} + apollo_router_cache_miss_time_count{storage=\"memory\"}) * 100\n",
     "legendFormat": "{{kind}} ({{storage}})"
    },
    {
     "expr": "apollo_router_cache_hit_time_count{storage=\"redis\"} / (apollo_router_cache_hit_time_count{storage=\"redis\"} + apollo_router_cache_miss_time_count{storage=\"redis\"}) * 100",
     "legendFormat": "{{kind}} ({{storage}})"
    }
   ]
  },
  {
   "title": "Query planning duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, apollo_router_query_planning_plan_duration_bucket)",
     "legendFormat": "apollo.router.query_planning.plan.duration p50"
    },
    {
     "expr": "histogram_quantile(0.75, apollo_router_query_planning_plan_duration_bucket)\n",
     "legendFormat": "apollo.router.query_planning.plan.duration p75"
    },
    {
     "expr": "histogram_quantile(0.90, apollo_router_query_planning_plan_duration_bucket)\n\n",
     "legendFormat": "apollo.router.query_planning.plan.duration p90"
    },
    {
     "expr": "histogram_quantile(0.95, apollo_router_query_planning_plan_duration_bucket)\n\n",
     "legendFormat": "apollo.router.query_planning.plan.duration p95"
    },
    {
     "expr": "histogram_quantile(0.99, apollo_router_query_planning_plan_duration_bucket)\n\n",
     "legendFormat": "apollo.router.query_planning.plan.duration p99"
    },
    {
     "expr": "histogram_quantile(1, apollo_router_query_planning_plan_duration_bucket)",
     "legendFormat": "apollo.router.query_planning.plan.duration max"
    }
   ]
  },
  {
   "title": "Query planner cache size (in memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apollo_router_cache_size{type=\"memory\"}",
     "legendFormat": "Cache size ({{kind}})"
    }
   ]
  },
  {
   "title": "Evaluated plans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_query_planning_plan_evaluated_plans_bucket[$__rate_interval])))",
     "legendFormat": "evaluated plans p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(apollo_router_query_planning_plan_evaluated_plans_bucket[$__rate_interval])))",
     "legendFormat": "evaluated plans p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_query_planning_plan_evaluated_plans_bucket[$__rate_interval])))",
     "legendFormat": "evaluated plans p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_plan_evaluated_plans_bucket[$__rate_interval])))",
     "legendFormat": "evaluated plans p95"
    }
   ]
  },
  {
   "title": "Query planner cache warmup time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_warmup_duration_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Entity cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "filters": [
      { "id": "872bc575", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "${traceId}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  }
 ]
}